name: test-worker
base: core18
version: git
grade: stable
summary: Travis CI worker
description: |-
 This snap is for internal use by Travis to run worker nodes.
confinement: strict

apps:
  daemon:
    command: daemon.start
    daemon: simple
    plugs:
      - lxd
      - network
      - network-bind
  travis-worker:
    command: bin/travis-worker
    plugs:
      - lxd
      - network
      - network-bind

parts:
  travis-worker:
    source: .
    build-packages:
      - gcc
    plugin: go
    go-packages:
      - github.com/travis-ci/worker/cmd/travis-worker
    go-importpath: github.com/travis-ci/worker
    go-channel: 1.14/stable
    prime:
      - bin/travis-worker
    override-build: |-
      set -eux

      cd ${SNAPCRAFT_PROJECT_DIR}
      VERSION="$(git describe --always --dirty --tags 2>/dev/null)"
      REVISION="$(git rev-parse HEAD)"
      REVISION_URL="https://github.com/travis-ci/worker/tree/${REVISION}"
      GENERATED="$(date -u +'%Y-%m-%dT%H:%M:%S%z')"
      COPYRIGHT="$(grep -i ^copyright LICENSE | sed 's/^[Cc]opyright //')"

      cd ${SNAPCRAFT_PART_SRC}
      sed -i "s#VersionString =.*#VersionString = \"${VERSION}\"#g" version.go
      sed -i "s#RevisionString =.*#RevisionString = \"${REVISION}\"#g" version.go
      sed -i "s#RevisionURLString =.*#RevisionURLString = \"${REVISION_URL}\"#g" version.go
      sed -i "s#GeneratedString =.*#GeneratedString = \"${GENERATED}\"#g" version.go
      sed -i "s#CopyrightString =.*#CopyrightString = \"${COPYRIGHT}\"#g" version.go

      set +ex
      snapcraftctl build
      set -ex

  wrappers:
    plugin: dump
    source: .snapcraft/
